version: '3.8'
services:
  proxy:
    container_name: websec-proxy
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
  db:
    container_name: websec-db
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - db:/data
  backend:
    container_name: websec-backend
    image: oven/bun:latest
    restart: always
    depends_on:
      - proxy
    working_dir: /app
    command: >
      sh -c "bun install &&
             bun run /app/server.js"
    volumes: 
      - ./backend:/app
  frontend:
    container_name: websec-frontend
    image: node:latest
    working_dir: /app
    command: >
      sh -c "npm install &&
             npm run dev --host"
    volumes:
      - ./frontend:/app



volumes:
  proxy:
    driver: local
  db:
    driver: local
  frontend:
    driver: local
  backend:
    driver: local
