version: '3.8'
services:
  db:
    container_name: db
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - db:/data
  #server: #still needs setup - not working
    #container_name: server
    #image: oven/bun:latest
    #restart: always
    #ports:
      #- '443:8080'
    #command: bun run server.js
    #volumes: 
      #- package.json:./
      #- bun.lockb:./
      #- src:/src
      #- server.js:server.js
volumes:
  db:
    driver: local