version: '3.8'
services:
  proxy:
    container_name: websec-proxy
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
  database:
    container_name: websec-db
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - database
  backend:
    container_name: websec-backend
    image: oven/bun:latest
    restart: always
    working_dir: /server
    command: >
      sh -c "bun install &&
             bun --hot index.ts"
    depends_on:
      - database
    volumes: 
      - ./server:/server
    networks:
      - default
      - database
  # frontend:
  #   container_name: websec-frontend
  #   image: node:latest
  #   working_dir: /app
  #   command: >
  #     sh -c "npm install &&
  #            npm run docker"
  #   volumes:
  #     - ./app:/app
volumes:
  proxy:
    driver: local
  database:
    driver: local
  frontend:
    driver: local
  backend:
    driver: local
networks:
  database: 
    driver: bridge
